name: Deploy Go App to Google Cloud Run with Redis Connector

on:
  push:
    branches:
      - main

env:
  PRODUCT_DETAIL_URL: https://go-app-a4688f4fbfb7465cda117fc8573cc42344af054b-937025550093.us-central1.run.app
  PROJECT_ID: scientific-host-421314
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 设置 Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          skip_install: false

      # 配置 Docker 使用 GCP 认证
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 构建并推送到 Google Container Registry
      - name: Build and Push Docker image
        run: |
          export IMAGE_NAME=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/keepa-search:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 部署到 Cloud Run 并连接 VPC 访问通道
      - name: Deploy to Cloud Run
        if: github.event_name != 'pull_request'
        run: |
          gcloud run deploy go-app-${{ github.sha }} \
            --image=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/keepa-search:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated\
            --port=8081 \
            --memory=256Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --set-env-vars=PRODUCT_DETAIL_URL=${{env.PRODUCT_DETAIL_URL}}